defaults:
  - _self_
  - model: mocov1
  - dataset: cifar10_mocov1

pretraining:
  epochs: 200
  
  optimizer:
    _target_: torch.optim.SGD
    lr: 0.03
    momentum: 0.9
    weight_decay: 1e-4
  
  train_dataloader:
    _target_: torch.utils.data.DataLoader
    batch_size: 256
    num_workers: 4
    shuffle: true
    pin_memory: true
    drop_last: true

  val_dataloader:
    _target_: torch.utils.data.DataLoader
    batch_size: 1
    num_workers: 4
    shuffle: false
    pin_memory: true
    drop_last: false

finetuning:
  epochs: 50
  batch_size: 256
  
  optimizer:
    _target_: torch.optim.SGD
    lr: 0.01
    momentum: 0.9

  train_dataloader:
    _target_: torch.utils.data.DataLoader
    batch_size: 256
    num_workers: 4
    shuffle: true
    pin_memory: true
    drop_last: true

  val_dataloader:
    _target_: torch.utils.data.DataLoader
    batch_size: 1
    num_workers: 4
    shuffle: false
    pin_memory: true
    drop_last: false